### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by Gigaxel** [Gigaxel/codesnap.sh#2]
Maybe a 100 code snippets per hour

**Comment by 4m1z** [comment]
I will take a look at this issue

**Comment by Gigaxel** [comment]
> I will take a look at this issue

nice. Thanks

**Comment by 4m1z** [comment]
I opened this https://github.com/Gigaxel/codesnap.sh/pull/11 for this issue

**Comment by Gigaxel** [comment]
> I opened this #11 for this issue

thanks. I left some comments

**Comment by shayanshabani** [comment]
Hello, I am interested to contribute to your project, I opened this pull request #14 for this issue. Good Luck!
