### ISSUE TITLE
Add custom TTL support

### ISSUE THREAD

**Issue by Gigaxel** [Gigaxel/codesnap.sh#5]
Currently every entry will be deleted after 24 hours. We also want to support a custom TTL up to 24 hours (maybe later extend it)

e.g. 

```
ssh codesnap.sh ttl=1000 < example.go
```

where the `ttl` is in seconds

**Comment by 4m1z** [comment]
I will work on this issue

**Comment by Gigaxel** [comment]
> I will work on this issue

you cannot work on this issue. You don't have server access xD

**Comment by Gigaxel** [comment]
also the TLS won't be set on the golang server, but on the nginx proxy
